-- THIS FILE IS AUTOGENERATED DO NOT EDIT
return {
  {{"keyword", "local"}, {"", " "}, {"keyword.function", "function"}, {"", " "}, {"function", "blog_add_next_prev"}, {"punctuation.bracket", "("}, {"variable.parameter", "manifest"}, {"punctuation.bracket", ")"}, {"", "\
"}},
  {{"", "\9"}, {"comment", "-- the list of blog posts created by a previous processor,"}, {"", "\
"}},
  {{"", "\9"}, {"comment", "-- which collected all pages under a blog subdirectory and"}, {"", "\
"}},
  {{"", "\9"}, {"comment", "-- then sorted the result by each page's publish date"}, {"", "\
"}},
  {{"", "\9"}, {"keyword", "local"}, {"", " "}, {"variable", "blog"}, {"", " "}, {"operator", "="}, {"", " "}, {"variable", "manifest"}, {"punctuation.delimiter", "."}, {"variable.member", "groups"}, {"punctuation.delimiter", "."}, {"variable.member", "blog"}, {"punctuation.delimiter", "."}, {"variable.member", "chrono"}, {"", "\
"}},
  {{"", "\9"}, {"keyword.repeat", "for"}, {"", " "}, {"variable", "i"}, {"", " "}, {"operator", "="}, {"", " "}, {"number", "1"}, {"punctuation.delimiter", ","}, {"", " "}, {"operator", "#"}, {"variable", "blog"}, {"", " "}, {"keyword.repeat", "do"}, {"", "\
"}},
  {{"", "\9\9"}, {"keyword.conditional", "if"}, {"", " "}, {"variable", "i"}, {"", " "}, {"operator", ">"}, {"", " "}, {"number", "1"}, {"", " "}, {"keyword.conditional", "then"}, {"", "\
"}},
  {{"", "\9\9\9"}, {"variable", "blog"}, {"punctuation.bracket", "["}, {"variable", "i"}, {"punctuation.bracket", "]"}, {"punctuation.delimiter", "."}, {"variable.member", "meta"}, {"punctuation.delimiter", "."}, {"variable.member", "next"}, {"", " "}, {"operator", "="}, {"", " "}, {"variable", "blog"}, {"punctuation.bracket", "["}, {"variable", "i"}, {"", " "}, {"operator", "-"}, {"", " "}, {"number", "1"}, {"punctuation.bracket", "]"}, {"", "\
"}},
  {{"", "\9\9"}, {"keyword.conditional", "end"}, {"", "\
"}},
  {{"", "\9\9"}, {"keyword.conditional", "if"}, {"", " "}, {"variable", "i"}, {"", " "}, {"operator", "<"}, {"", " "}, {"operator", "#"}, {"variable", "blog"}, {"", " "}, {"keyword.conditional", "then"}, {"", "\
"}},
  {{"", "\9\9\9"}, {"variable", "blog"}, {"punctuation.bracket", "["}, {"variable", "i"}, {"punctuation.bracket", "]"}, {"punctuation.delimiter", "."}, {"variable.member", "meta"}, {"punctuation.delimiter", "."}, {"variable.member", "prev"}, {"", " "}, {"operator", "="}, {"", " "}, {"variable", "blog"}, {"punctuation.bracket", "["}, {"variable", "i"}, {"", " "}, {"operator", "+"}, {"", " "}, {"number", "1"}, {"punctuation.bracket", "]"}, {"", "\
"}},
  {{"", "\9\9"}, {"keyword.conditional", "end"}, {"", "\
"}},
  {{"", "\9"}, {"keyword.repeat", "end"}, {"", "\
"}},
  {{"keyword.function", "end"}}
}
