-- THIS FILE IS AUTOGENERATED DO NOT EDIT
return {
  {{"function.call", "Rule"}, {"", " "}, {"string", "'#navbar'"}, {"", " "}, {"constructor", "{"}, {"", "\
"}},
  {{"", "\9"}, {"property", "display"}, {"", " "}, {"operator", "="}, {"", " "}, {"variable", "flex"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9"}, {"property", "align_items"}, {"", " "}, {"operator", "="}, {"", " "}, {"variable", "center"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9"}, {"property", "overflow_x"}, {"", " "}, {"operator", "="}, {"", " "}, {"variable", "auto"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9"}, {"property", "overflow_y"}, {"", " "}, {"operator", "="}, {"", " "}, {"variable", "hidden"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9"}, {"comment", "-- ..."}, {"", "\
"}},
  {{"constructor", "}"}}
}
