-- THIS FILE IS AUTOGENERATED DO NOT EDIT
return {
  {{"keyword", "local"}, {"", " "}, {"variable", "dom"}, {"", " "}, {"operator", "="}, {"", " "}, {"function.call", "body"}, {"", " "}, {"constructor", "{"}, {"", "\
"}},
  {{"", "\9"}, {"function.call", "h1"}, {"", " "}, {"string", "'Hello world!'"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9"}, {"function.call", "p"}, {"", " "}, {"constructor", "{"}, {"", "\
"}},
  {{"", "\9\9"}, {"string", "'A minimal Lua '"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9\9"}, {"function.call", "a"}, {"", " "}, {"constructor", "{"}, {"", "\
"}},
  {{"", "\9\9\9"}, {"property", "href"}, {"", " "}, {"operator", "="}, {"", " "}, {"string", "'https://github.com/Apeiros-46B/lwk'"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9\9\9"}, {"string", "'static site generator'"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9\9"}, {"constructor", "}"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9"}, {"constructor", "}"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"constructor", "}"}}
}
