-- THIS FILE IS AUTOGENERATED DO NOT EDIT
return {
  {{"comment", "-- other stuff"}, {"", "\
"}},
  {{"", "\
"}},
  {{"function.call", "SideNote"}, {"", " "}, {"constructor", "{"}, {"", "\
"}},
  {{"", "\9"}, {"comment", "-- class is added, does not overwrite original"}, {"", "\
"}},
  {{"", "\9"}, {"property", "class"}, {"", " "}, {"operator", "="}, {"", " "}, {"string", "'my-added-class'"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9"}, {"function.call", "p"}, {"", " "}, {"string", "'This element is appended as a child'"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9"}, {"function.call", "ul"}, {"", " "}, {"constructor", "{"}, {"", "\
"}},
  {{"", "\9\9"}, {"function.call", "li"}, {"", " "}, {"string", "\"It doesn't care what you append\""}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9\9"}, {"function.call", "li"}, {"", " "}, {"string", "'This works too'"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9"}, {"constructor", "}"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"constructor", "}"}, {"", "\
"}},
  {{"", "\
"}},
  {{"comment", "-- other stuff"}}
}
