-- THIS FILE IS AUTOGENERATED DO NOT EDIT
return {
  {{"function.call", "GlobalStyles"}, {"", " "}, {"constructor", "{"}, {"", "\
"}},
  {{"", "\9"}, {"function.call", "Rule"}, {"", " "}, {"string", "'.sidenote'"}, {"", " "}, {"constructor", "{"}, {"", "\
"}},
  {{"", "\9\9"}, {"property", "padding"}, {"", " "}, {"operator", "="}, {"", " "}, {"function.call", "rem"}, {"punctuation.bracket", "("}, {"number", "1"}, {"punctuation.bracket", ")"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9\9"}, {"property", "width"}, {"", " "}, {"operator", "="}, {"", " "}, {"variable", "fit_content"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9\9"}, {"property", "max_width"}, {"", " "}, {"operator", "="}, {"", " "}, {"function.call", "pct"}, {"punctuation.bracket", "("}, {"number", "100"}, {"punctuation.bracket", ")"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9\9"}, {"property", "font_size"}, {"", " "}, {"operator", "="}, {"", " "}, {"function.call", "pct"}, {"punctuation.bracket", "("}, {"number", "90"}, {"punctuation.bracket", ")"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9\9"}, {"property", "border_left"}, {"", " "}, {"operator", "="}, {"", " "}, {"constructor", "{"}, {"", " "}, {"function.call", "px"}, {"punctuation.bracket", "("}, {"number", "4"}, {"punctuation.bracket", ")"}, {"punctuation.delimiter", ","}, {"", " "}, {"variable", "solid"}, {"punctuation.delimiter", ","}, {"", " "}, {"function.call", "var"}, {"", " "}, {"string", "'fg_sep'"}, {"", " "}, {"constructor", "}"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9\9"}, {"property", "background_color"}, {"", " "}, {"operator", "="}, {"", " "}, {"function.call", "var"}, {"", " "}, {"string", "'bg_raised'"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9\9"}, {"property", "color"}, {"", " "}, {"operator", "="}, {"", " "}, {"function.call", "var"}, {"", " "}, {"string", "'fg_dim'"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9"}, {"constructor", "}"}, {"", "\
"}},
  {{"constructor", "}"}, {"", "\
"}},
  {{"", "\
"}},
  {{"keyword.return", "return"}, {"", " "}, {"function.call", "aside"}, {"", " "}, {"constructor", "{"}, {"", "\
"}},
  {{"", "\9"}, {"property", "class"}, {"", " "}, {"operator", "="}, {"", " "}, {"string", "'sidenote'"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9"}, {"property", "role"}, {"", " "}, {"operator", "="}, {"", " "}, {"string", "'note'"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"constructor", "}"}}
}
