-- THIS FILE IS AUTOGENERATED DO NOT EDIT
return {
  {{"keyword.return", "return"}, {"", " "}, {"function.call", "Document"}, {"", " "}, {"constructor", "{"}, {"", "\
"}},
  {{"", "\9"}, {"property", "lang"}, {"", " "}, {"operator", "="}, {"", " "}, {"string", "'en'"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9"}, {"function.call", "head"}, {"", " "}, {"constructor", "{"}, {"", "\
"}},
  {{"", "\9\9"}, {"function.call", "meta"}, {"", " "}, {"constructor", "{"}, {"", " "}, {"property", "charset"}, {"", " "}, {"operator", "="}, {"", " "}, {"string", "'UTF-8'"}, {"", " "}, {"constructor", "}"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9\9"}, {"function.call", "title"}, {"", " "}, {"string", "'Hello world!'"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9"}, {"constructor", "}"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"", "\9"}, {"function.call", "body"}, {"punctuation.bracket", "("}, {"function.call", "p"}, {"", " "}, {"string", "'Hello from Lua!'"}, {"punctuation.bracket", ")"}, {"punctuation.delimiter", ","}, {"", "\
"}},
  {{"constructor", "}"}}
}
